# Generated by Django 3.1.6 on 2021-02-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comolete',
            new_name='complete',
        ),
    ]
