# Generated by Django 3.1.7 on 2021-03-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210225_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='2213424.jpg', null=True, upload_to=''),
        ),
    ]
